spring:
  config:
    import:
      - optional:file:env/secret.env[.properties]

  profiles:
    active:
      - telegram
    group:
      email:
        - email
      telegram:
        - telegram

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${oauth2_kakao_client-id}
            redirect-uri: http://localhost:8080/api/login/oauth2/code/kakao
            client-authentication-method: POST
            client-secret: ${client-secret}
            scope:
              - account_email
            client_name: kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    host: smtp.naver.com
    port: 465
    username: cloudwi@naver.com
    password: ${email_password}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

secret:
  telegramToken: ${telegramToken}
  chat_id: ${chat_id}
  bot_name: ${bot_name}
  oauth2_kakao_client-id: ${oauth2_kakao_client-id}
  client-secret: ${client-secret}